version: "3.7"
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYROOT_PASSWORD=1234
    volumes:
      - dbencode:/etc/mysql
      - C:\Users\박범선\datadir:/var/lib/mysql
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - C:\Users\박범선\datadirmongo:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - C:\Users\박범선\redis_datadir:/data

volumes:
  dbencode: