spring:
  profiles: sun

---

spring:
  profiles: mac

---

spring:
  profiles: win

---

spring:
  profiles:
    active: dev
    include: oauth2, secret_key


logging:
  level:
    jdbc:
      sqlonly=debug: debug
    org.springframework.data.mongodb: DEBUG
