spring:
  profiles: dev

---

spring:
  profiles: mac

---

spring:
  profiles: win

---

spring:
  profiles:
    active: sun
    include: oauth2, secret_key


logging:
  level:
    jdbc:
      sqlonly=debug: debug

logging.level.org.springframework.data.mongodb: DEBUG