### POST create member
POST http://localhost:8080/mongo-api/join
Content-Type: application/json
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

{
  "email": "email1",
  "nickname": "nickname1",
  "password": "password1"
}

### GET get member detail
GET http://localhost:8080/mongo-api/member/61b0d7ac3ae29b4df74720a5
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

### PUT update member
PUT http://localhost:8080/mongo-api/member/61b0d7ac3ae29b4df74720a5
Content-Type: application/json
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

{
  "nickname": "nickname1",
  "profileImage": null,
  "introduce": "introduce1",
  "gender": "MAN"
}

### PUT update member password
PUT http://localhost:8080/mongo-api/member/61b0d7ac3ae29b4df74720a5/password
Content-Type: application/json
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

{
  "password": "password1",
  "checkPassword": "password1"
}

### GET find cart item list by id
GET http://localhost:8080/mongo-api/members/61a7ad5707fe686bf8a2fb76/cart
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

### POST create cart item
POST http://localhost:8080/mongo-api/members/61a7ad5707fe686bf8a2fb76/cart
Content-Type: application/json
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

{
  "productId": "61a7a5246e57565fe532a3fe",
  "quantity": 1
}

### POST update cart item product quantity
PUT http://localhost:8080/mongo-api/members/61a7ad5707fe686bf8a2fb76/cart
Content-Type: application/json
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

{
  "cartItemId": "61a7d84465d08a56db80d7b1",
  "quantity": 1
}
