### GET users
GET http://localhost:8080/api/users
Accept: application/vnd.com.manduljo.ohou.v1+json

### GET user by name
GET http://localhost:8080/api/users
Content-Type: application/json
Accept: application/vnd.com.manduljo.ohou.v1+json

{
  "name": "name1"
}

### GET user by id
GET http://localhost:8080/api/users/61648e2acb53a12a8098295c
Accept: application/vnd.com.manduljo.ohou.v1+json

### POST User
POST localhost:8080/api/users
Content-Type: application/json
Accept: application/vnd.com.manduljo.ohou.v1+json

{
  "name": "name3",
  "age": 3
}

###
