### GET get product detail
GET http://localhost:8080/mongo-api/products/61b5f0106824a1dc04292575
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

### GET find product list by search text
GET http://localhost:8080/mongo-api/products/search?search=소파&page=0
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8

### GET find product list by category
GET http://localhost:8080/mongo-api/store?category=61a3ac109a7e455a429e3442&page=0
Accept: application/vnd.com.manduljo.ohou.v1+json;charset=UTF-8